apiVersion: v1
kind: Service
metadata:
  name: aiops-cluster
  namespace: aiops-postgres
spec:
  selector:
    application: spilo
    cluster-name: aiops-cluster
    spilo-role: master
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: LoadBalancer
